name: Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Create Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        prerelease: false
    - name: Publish to Crates.io
      uses: katyo/publish-crates@v1
      with: 
        dry-run: true

      
